# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Test-10-1-15' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
pod 'PGFramework'
pod 'Firebase/Analytics'
pod 'Firebase/Database'
pod 'FirebaseAuth'
  # Pods for Test-10-1-15

  target 'Test-10-1-15Tests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Test-10-1-15UITests' do
    # Pods for testing
  end

end
